apiVersion: v1
kind: Service
metadata:
  name: diabetes-score-service
spec:
  selector:
    app: diabetes-score
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diabetes-score
spec:
  selector:
    matchLabels:
      app: diabetes-score
  replicas: 4
  template:
    metadata:
      labels:
        app: diabetes-score
    spec:
      containers:
      - name: diabetes-score
        image: diabetes-score:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000